# -*- coding: utf-8 -*-
"""Edited FasterRCNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSfiblgkMLkmzVQR0Hsq1eXc8456V5_n
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x

!pip install keras==2.0.3

import pandas
import numpy
import os
import matplotlib
import cv2
import sklearn
import h5py

from google.colab import drive
drive.mount('/content/drive/')

!unzip -uq "/content/drive/My Drive/fasterRCNN.zip" -d "/content/"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/original/
!python train_frcnn.py -o simple -p annotate.txt

!python test_frcnn.py -p test_images

pip install gmplot

import gmplot
import pandas as pd

coordinates = pd.read_csv('coordinates.csv')

latitude_list = coordinates['Latitude'].tolist()
longitude_list = coordinates['Longitude'].tolist()

gmap1 = gmplot.GoogleMapPlotter(24.929983, 67.114831, 13 ) 
gmap1.scatter( latitude_list, longitude_list, '# FF0000', size = 0.1, marker = False )

gmap1.draw("PipelineMap.html")